apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulate-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulate-workload
  template:
    metadata:
      labels:
        app: simulate-workload
    spec:
      containers:
      - name: simulate-workload
        image: shlomigis/simulate-workload:latest
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        ports:
        - containerPort: 5000