apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-simulate-workload
spec:
  scaleTargetRef:
    name: simulate-workload
    kind: Deployment   
  pollingInterval: 15
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"